<div class="col-lg-3">
    <div class="card profile-navigate">
        <div class="card-body pb-0">
            <ul class="profile-routes list-unstyled">
                <li class="profile-item">
                    <a href="/admin/dashboard" class="">
                        <i class="fal fa-cog"></i>
                        <span>Cài đặt website</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/shop" class="">
                        <i class="fal fa-store-alt"></i>
                        <span>Danh sách shop</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/member" class="">
                        <i class="fal fa-user-circle"></i>
                        <span>Danh sách tài khoản</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/post" class="">
                    <i class="fal fa-newspaper"></i>
                        <span>Danh sách bài đăng</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/rut" class="">
                    <i class="fal fa-sack-dollar"></i>
                        <span>Yêu cầu rút tiền</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/bank" class="">
                        <i class="fal fa-university"></i>
                        <span>Ngân hàng nạp tiền</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/admin/card" class="">
                        <i class="fal fa-credit-card-blank"></i>
                        <span>Lịch sử nạp thẻ cào</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>