<div class="col-lg-3">
    <div class="card profile-navigate">
        <div class="card-body pb-0">
            <ul class="profile-routes list-unstyled">
                <li class="profile-item">
                    <a href="/thong-tin" class="">
                        <i class="fal fa-user-circle"></i>
                        <span>Thông tin</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/thong-tin/doi-mat-khau" class="">
                        <i class="fal fa-lock"></i>
                        <span>Đổi mật khẩu</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/thong-tin/nap-tien" class="">
                        <i class="fal fa-wallet"></i>
                        <span>Lịch sử nạp tiền</span>
                    </a>
                </li>
                <li class="profile-item">
                    <a href="/thong-tin/nap-the-cao" class="">
                        <i class="fal fa-credit-card-blank"></i>
                        <span>Lịch sử nạp thẻ cào</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>