<?php include_once __DIR__ . '/../layouts/head.phtml'; 
include_once __DIR__ . '/../layouts/navbar.phtml'; 
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h2 class="page-title">Thông tin</h2>
            <div class="row">
                <?php include_once __DIR__ . '/menu.phtml'; ?>
                <div class="col-lg-9 info-container">
                    <div>
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Đổi mật khẩu</h5>
                                <form action="/api/profile/change-password" method="POST" next>
                                    <div class="form-group">
                                        <label for="">Mật khẩu cũ:</label>
                                        <input type="password" name="password" required="required" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="">Mật khẩu mới:</label>
                                        <input type="password" name="new_password" required="required" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="">Nhập lại mật khẩu mới:</label> 
                                        <input type="password" name="confirm_new_password" required="required" class="form-control">
                                    </div> 
                                    <button class="ta-submit btn btn-main w-100" type="submit">Đổi mật khẩu</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php 
include_once __DIR__ . '/../layouts/footer.phtml'; 
include_once __DIR__ . '/../layouts/script.phtml'; 
?>
<script>
$(function() {
    $('.profile-item a[href="' + location.pathname + '"]').addClass('nuxt-link-exact-active nuxt-link-active')
        .attr("aria-current", "page").parent(1).addClass('active')
});
</script>
<?php
include_once __DIR__ . '/../layouts/end.phtml'; 
?>