<?php include_once __DIR__ . '/../../layouts/head.phtml';
include_once __DIR__ . '/../../layouts/navbar.phtml';
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h4 class="page-title d-flex align-items-center justify-content-between">
                Quản lý Shop
                <a href="/shop/<?=Auth::user()->username;?>" class="fs-12 btn btn-outline-main btn-sm"><i
                        class="fad fa-store-alt"></i>Xem shop
                </a>
            </h4>
            <div class="row">
                <div class="col-lg-3">
                    <div class="card shadow-none border bg-transparent">
                        <div class="card-body shadow-none pt-2 pb-0">
                            <ul class="seller-menu ps-0">
                                <li class="item text"><span class="text">Tổng quan</span></li>
                                <li class="item"><a href="/seller" class="nuxt-link-active"><i
                                            class="fad fa-analytics"></i> <span>Thống kê</span></a></li>
                                <li class="item"><a href="/seller/rating" class=""><i class="fad fa-star"></i>
                                        <span>Đánh giá</span></a></li>
                                <li class="item text"><span class="text">Tài khoản</span></li>
                                <li class="item"><a href="/seller/account/add" class=""><i
                                            class="fad fa-plus-circle"></i> <span>Thêm tài khoản</span></a></li>
                                <li class="item"><a href="/seller/account" class=""><i class="fad fa-tags"></i>
                                        <span>Tất cả tài khoản</span></a></li>
                                <li></li>
                                <li class="item"><a href="/seller/account/orders" class=""><i
                                            class="fad fa-user-tag"></i> <span>Tài khoản đã bán</span></a></li>
                                <li></li>
                                <li class="item text"><span class="text">Khuyến mãi</span></li>
                                <li class="item"><a href="/seller/promo/create"
                                      ><i
                                            class="fad fa-money-check"></i> <span>Thêm mã khuyến mãi</span></a></li>
                                <li class="item"><a href="/seller/promo"  class="nuxt-link-exact-active nuxt-link-active" aria-current="page"><i
                                            class="fad fa-th-list"></i> <span>Quản lý mã khuyến mãi</span></a></li>
                                <li class="item text"><span class="text">Khác</span></li>
                                <li class="item"><a href="/seller/withdraw" class=""><i class="fad fa-wallet"></i>
                                        <span>Rút tiền</span></a></li>
                                <li class="item"><a href="/seller/setting" class=""><i class="fad fa-cog"></i> <span>Cài
                                            đặt</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="seller-container col-lg-9">
                    <div class="card">
                        <div class="card-body">
                            <!---->
                            <a href="/seller/promo" class="d-block text-primary fs-14 fw-bold pb-3"><i class="fa fa-arrow-left"></i>
                                Trở lại
                            </a>
                            <h5 class="card-title">
                                Cập nhật mã khuyến mãi
                            </h5>
                            <form action="/api/seller/promo/<?=$promo->id;?>/edit" method="POST" next>
                                <div class="form-group">
                                    <label for="">Mã khuyến mãi:</label>
                                    <input type="text" name="code" required="required" value="<?=$promo->code;?>"
                                        class="form-control">
                                    <p class="help-block">
                                        * Ví dụ: KM2023, GIAM10K, KHAITRUONG2023, SHOPKM5 (lưu ý mã tối thiểu 5 và tối
                                        đa 15 ký tự, không có khoảng cách và được viết hoa tất cả)
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label for="">Số lần sử dụng tối đa:</label>
                                    <input placeholder="" name="count" value="<?=$promo->count;?>" type="tel"
                                        class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="">Giá trị tối thiểu để sử dụng:</label>
                                    <input placeholder="" name="usemin" value="<?=$promo->usemin;?>" type="tel"
                                        class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="">Giảm giá:</label>
                                    <div class="form-check">
                                        <input type="radio" name="type" onchange="loai_giamgia()" value="percent"
                                            id="radio-with-2" class="form-check-input"
                                            <?=($promo->type == 'percent') ? 'checked' : '';?>>
                                        <label for="radio-with-2" class="form-check-label pb-0">
                                            Theo phần trăm (%)
                                        </label>
                                        <p class="help-block mt-1">
                                            * Tài khoản giá 100,000 sử dụng mã giảm 20% (giá acc sẽ còn 80,000)
                                        </p>
                                    </div>
                                    <div class="form-check">
                                        <input type="radio" name="type" onchange="loai_giamgia()" value="money"
                                            id="radio-with" class="form-check-input"
                                            <?=($promo->type == 'money') ? 'checked' : '';?>>
                                        <label for="radio-with" class="form-check-label pb-0">
                                            Theo số tiền nhất định
                                        </label>
                                        <p class="help-block mt-1">
                                            * Tài khoản giá 100,000 sử dụng mã giảm 20,000 (giá acc sẽ còn 80,000)
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" id="type_name">loading...</label>
                                    <input type="text" name="quantity" value="<?=$promo->quantity;?>"
                                        class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="">Được áp dụng:</label>
                                    <select name="game" class="form-control">
                                        <option value="all" <?=($promo->game == 'all') ? 'selected' : '';?>>Tất cả tài
                                            khoản</option>
                                        <option value="lien-quan" <?=($promo->game == 'lien-quan') ? 'selected' : '';?>>
                                            Chỉ tài khoản Liên Quân</option>
                                        <option value="genshin-impact"
                                            <?=($promo->game == 'genshin-impact') ? 'selected' : '';?>>Chỉ tài khoản
                                            Genshin Impact</option>
                                        <option value="free-fire" <?=($promo->game == 'free-fire') ? 'selected' : '';?>>
                                            Chỉ tài khoản Free Fire</option>
                                        <option value="roblox" <?=($promo->game == 'roblox') ? 'selected' : '';?>>Chỉ
                                            tài khoản Roblox</option>
                                        <option value="ngoc-rong-online"
                                            <?=($promo->game == 'ngoc-rong-online') ? 'selected' : '';?>>Chỉ tài khoản
                                            Ngọc Rồng</option>
                                        <option value="fifa-online"
                                            <?=($promo->game == 'fifa-online') ? 'selected' : '';?>>Chỉ tài khoản Fifa
                                            Online</option>
                                        <option value="dot-kich" <?=($promo->game == 'dot-kich') ? 'selected' : '';?>>
                                            Chỉ tài khoản Đột Kích</option>
                                        <option value="pubg-mobile"
                                            <?=($promo->game == 'pubg-mobile') ? 'selected' : '';?>>Chỉ tài khoản PUBG
                                            Mobile</option>
                                        <option value="lien-minh" <?=($promo->game == 'lien-minh') ? 'selected' : '';?>>
                                            Chỉ tài khoản Liên Minh</option>
                                        <option value="toc-chien" <?=($promo->game == 'toc-chien') ? 'selected' : '';?>>
                                            Chỉ tài khoản Tốc Chiến</option>
                                        <option value="zing-speed-mobile"
                                            <?=($promo->game == 'zing-speed-mobile') ? 'selected' : '';?>>Chỉ tài khoản
                                            Zing Speed</option>
                                        <option value="play-together"
                                            <?=($promo->game == 'play-together') ? 'selected' : '';?>>Chỉ tài khoản Play
                                            Together</option>
                                    </select>
                                </div>
                                <button class="ta-submit btn btn-main w-100" type="submit">Cập nhập mã</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
include_once __DIR__ . '/../../layouts/footer.phtml';
include_once __DIR__ . '/../../layouts/script.phtml';
?>
<script>
function loai_giamgia() {
    var type = $("[name=type]:checked").val();
    (type == "money") ? $("#type_name").text("số tiền nhất định :"): $("#type_name").text("Nhập phần trăm (%):")
}

$(document).ready(function() {
    loai_giamgia();
})
</script>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>