<?php include_once __DIR__ . '/../../layouts/head.phtml'; 
include_once __DIR__ . '/../../layouts/navbar.phtml'; 
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h4 class="page-title d-flex align-items-center justify-content-between">
                Quản lý Shop
                <a href="/shop/<?=Auth::user()->username;?>" class="fs-12 btn btn-outline-main btn-sm"><i
                        class="fad fa-store-alt"></i>Xem shop
                </a>
            </h4>
            <div class="row">
                <div class="col-lg-3">
                    <div class="card shadow-none border bg-transparent">
                        <div class="card-body shadow-none pt-2 pb-0">
                            <ul class="seller-menu ps-0">
                                <li class="item text"><span class="text">Tổng quan</span></li>
                                <li class="item"><a href="/seller" class="nuxt-link-active"><i
                                            class="fad fa-analytics"></i> <span>Thống kê</span></a></li>
                                <li class="item"><a href="/seller/rating" class=""><i class="fad fa-star"></i>
                                        <span>Đánh giá</span></a></li>
                                <li class="item text"><span class="text">Tài khoản</span></li>
                                <li class="item"><a href="/seller/account/add" class=""><i
                                            class="fad fa-plus-circle"></i> <span>Thêm tài khoản</span></a></li>
                                <li class="item"><a href="/seller/account" class=""><i class="fad fa-tags"></i>
                                        <span>Tất cả tài khoản</span></a></li>
                                <li></li>
                                <li class="item"><a href="/seller/account/orders" class=""><i
                                            class="fad fa-user-tag"></i> <span>Tài khoản đã bán</span></a></li>
                                <li></li>
                                <li class="item text"><span class="text">Khuyến mãi</span></li>
                                <li class="item"><a href="/seller/promo/create" class=""><i
                                            class="fad fa-money-check"></i> <span>Thêm mã khuyến mãi</span></a></li>
                                <li class="item"><a href="/seller/promo" class="nuxt-link-exact-active nuxt-link-active"
                                        aria-current="page"><i class="fad fa-th-list"></i> <span>Quản lý mã khuyến
                                            mãi</span></a></li>
                                <li class="item text"><span class="text">Khác</span></li>
                                <li class="item"><a href="/seller/withdraw" class=""><i class="fad fa-wallet"></i>
                                        <span>Rút tiền</span></a></li>
                                <li class="item"><a href="/seller/setting" class=""><i class="fad fa-cog"></i> <span>Cài
                                            đặt</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="seller-container col-lg-9">
                    <div>
                        <div class="card">
                            <div class="card-body card-table pb-0">
                                <h5 class="card-title">Danh sách mã khuyến mãi</h5>
                                <table class="table table-hover table-borderless">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Thao tác</th>
                                            <th>Áp dụng</th>
                                            <th>Mã KM</th>
                                            <th>Đã sử dụng</th>
                                            <th>Giảm giá</th>
                                            <th>Giá trị tối thiểu</th>
                                            <th>Thời gian</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach(Promo::find(['ShopID'=>Shop::my()->id])->all() as $item): ?>
                                        <tr> 
                                            <td><?=$item->id;?></td>
                                            <td>
                                                <a href="/seller/promo/<?=$item->id;?>/edit"
                                                    class="btn btn-primary btn-action">
                                                    <i class="fa fa-pencil-alt"></i></a>
                                                <a href="/seller/promo/<?=$item->id;?>/delete">
                                                    <button class="btn btn-danger btn-action">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </a>
                                            </td>
                                            <td><?=Promo::game($item->game);?></td>
                                            <td><?=$item->code;?></td>
                                            <td><?=$item->used;?></td>
                                            <td><?=$item->quantity;?></td>
                                            <td><?=$item->usemin;?></td>
                                            <td><?=timeago($item->createDate);?></td>
                                        <tr>
                                        <?php endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!---->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php 
include_once __DIR__ . '/../../layouts/footer.phtml'; 
include_once __DIR__ . '/../../layouts/script.phtml'; 
include_once __DIR__ . '/../../layouts/end.phtml'; 
?>