<!DOCTYPE html>
<html mode="">
<!--Design by YoDy DEV | zalo: 0986379490 -->

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title><?=Setting::find("title");?></title>
    <meta name="description" content="<?=Setting::find("description");?>">
    <meta name="keywords" content="<?=Setting::find("keywords");?>">
    <meta name="author" content="<?=Setting::find("copyright");?>">
    <meta name="theme-color" content="#fff">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" rel="stylesheet">
    <link rel='stylesheet' type='text/css' media='screen' href='/css/styles.css?v=<?=time();?>'>
    <link rel='stylesheet' type='text/css' media='screen' href='/css/app.css?v=<?=time();?>'>
    <link rel='stylesheet' type='text/css' media='screen' href='/css/animation.css?v=<?=time();?>'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<!--Design by YoDy DEV | zalo: 0986379490 -->

<body>