<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>


<!--Design by YoDy DEV | zalo: 0986379490 -->

<script src="/js/app.js?v=<?=time();?>"></script>

<script>
// Pusher.logToConsole = true;
// var pusher = new Pusher('846dc9bc93824aec119b', {
//     cluster: 'ap1'
// });

// var channel = pusher.subscribe('busy-summit-680');
// channel.bind('notify', function(data) {
//     noti(data.status, data.message);
//     if (data.href) {
//         var load = setInterval(() => {
//             window.location.href = data.href;
//             clearInterval(load);
//         }, 700)
//     }
// });
</script>