<?php include_once __DIR__ . '/layouts/head.phtml'; 
include_once __DIR__ . '/layouts/navbar.phtml'; 
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div class="ta-404 d-flex align-items-center flex-column justify-content-center min-h-450">
            <div class="text-center">
                <div class="img"><img height="240" alt="" src="/img/404.png" class="mw-100"></div>
                <h2 class="fw-bold mt-4 mb-2 fs-3">Không tìm thấy nội dung.</h2> <a href="/"
                    class="nuxt-link-active">Trở lại trang chủ</a>
            </div>
        </div>
    </div>
</div>
<?php 
include_once __DIR__ . '/layouts/footer.phtml'; 
include_once __DIR__ . '/layouts/script.phtml'; 
include_once __DIR__ . '/layouts/end.phtml'; 
?>