<?php include_once __DIR__ . '/../layouts/head.phtml';
include_once __DIR__ . '/../layouts/navbar.phtml';
// include_once __DIR__ . '/../layouts/menu.phtml';
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h2 class="page-title d-flex align-items-center">
                <img data-src="/categories/<?=$acc->game;?>.jpg" height="30" title="Logo <?=Game::type($acc->game);?>"
                    alt="Logo <?=Game::type($acc->game);?>" data-not-lazy="" src="/categories/<?=$acc->game;?>.jpg"
                    class="rounded"> <span class="ps-2">
                    Tài khoản <?=Game::type($acc->game);?> #<?=$acc->id;?>
                </span>
            </h2>
            <!---->
            <div class="ta-account-view mb-4">
                <div class="row">
                    <div class="col-xl-7 mb-2 mb-xl-0">
                        <!---->
                        <div class="position-relative">
                            <div class="slide-main">
                                <?php $i = 1;$m = 1;$num = 0;foreach (json_decode($acc->images) as $img): $num++;?>
                                <div>
                                    <div tabIndex="-1" style="width:100%;display:inline-block;">
                                        <img data-src="<?=$img;?>"
                                            title="Ảnh <?=$i++;?> Tài khoản <?=Game::type($acc->game);?> #<?=$acc->id;?>"
                                            alt="Ảnh <?=$m++;?> Tài khoản <?=Game::type($acc->game);?> #<?=$acc->id;?>"
                                            data-not-lazy="" src="<?=$img;?>" style="width:100%" class="rounded">
                                    </div>
                                </div>
                                <?php endforeach;?>
                            </div>
                            <div class="slide-footer">
                                <div class="d-flex align-items-center justify-content-between mx-2 mx-sm-3">
                                    <span class="fs-13 text-white cursor-pointer slide-zoom"><i
                                            class="fad fa-search-plus"></i> Xem ảnh phóng to
                                    </span> <span class="fs-13 text-white rounded px-2 bg-primary">
                                        <?=$num;?> / <b><?=$num;?></b></span>
                                </div>
                            </div>
                        </div>

                        <!---->
                        <div class="transform-0 slide-container slick-account-images slick-slider">
                            <?php $i = 1;foreach (json_decode($acc->images) as $img): ?>
                            <div tabindex="-1" style="width: 100%; display: inline-block;">
                                <div class="img-slider cursor-pointer position-relative">
                                    <div>
                                        <img title="Ảnh 1 Tài khoản <?=Game::type($acc->game);?> #15"
                                            alt="Ảnh 1 Tài khoản <?=Game::type($acc->game);?> #15"
                                            class="img-fluid rounded" src="<?=$img;?>">
                                    </div>
                                    <div class="slick-index fs-12 text-white bg-primary">
                                        <?=$i++;?>
                                    </div>
                                </div>
                            </div>
                            <?php endforeach;?>
                        </div>

                        <button class="btn btn-light w-100 my-2 share-link"><i class="fad fa-share-square"></i>
                            Chia sẻ liên kết
                        </button>
                    </div>

                    <div class="col-xl-5">
                        <div class="card">

                            <div class="seller-profile bg-profile rounded-top">
                                <div class="seller d-flex align-items-center p-3">
                                    <div class="avatar"><img height="42" alt="" class="rounded-circle shadow-sm"
                                            src="<?=$User->avatar;?>">
                                    </div>
                                    <div class="ps-2">
                                        <h4 class="group fs-14 mb-0"><span
                                                class="text-break name"><?=$User->fullname;?></span>
                                            <span class="text-muted">(<?=$User->username;?>)</span>
                                        </h4> <a href="/shop/<?=$User->username;?>" class="fs-13 pt-1 d-block">Xem cửa
                                            hàng</a>
                                    </div>
                                </div>
                                <div class="pt-0 p-3">
                                    <div class="seller-contacts">
                                        <h5 class="fs-13 text-secondary fw-normal small pb-1">
                                            Kiểm tra liên hệ trước khi mua:
                                        </h5>
                                        <div class="row gx-3">
                                            <div class="col-4">
                                                <?php if(!empty($shop->facebook)):?>
                                                <div class="seller-contact"><a
                                                        href="<?=$shop->facebook;?>" target="_blank"
                                                        class="btn btn-light bg-white d-block btn-sm"><img height="20"
                                                            src="/img/facebook.png"></a>
                                                </div>
                                                <?php endif;?>
                                            </div>
                                            <div class="col-4">
                                                <?php if(!empty($shop->zalo)):?>
                                                <div class="seller-contact"><a href="<?=$shop->zalo;?>"
                                                        target="_blank"
                                                        class="btn btn-light bg-white d-block btn-sm"><img height="20"
                                                            src="/img/zalo.png"></a>
                                                </div>
                                                <?php endif;?>

                                            </div>
                                            <div class="col-4">
                                                <?php if(!empty($shop->hotline)):?>
                                                <div class="seller-contact"><a href="tel:+84<?=substr($shop->hotline,1);?>"
                                                        class="btn btn-light bg-white d-block btn-sm"><i height="20"
                                                            class="fad fa-phone-plus text-primary"></i></a></div>
                                                <?php endif;?>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <p class="fs-13 description text-pre-wrap"><?=$acc->describe;?></p>
                                <div class="ta-account-info">
                                    <h5 class="text-dark mb-3 fw-normal fs-14">Thông tin về tài khoản:</h5>
                                    <table class="table table-inverse">
                                        <tbody>

                                            <?php $data = json_decode($acc->data);?>
                                            <?php if ($acc->game == 'free-fire' ): ?>
                                            <tr>
                                                <td>Skin súng</td>
                                                <td class="text-start"><strong><?=$data->skin;?></strong></td>
                                            </tr>
                                            <tr>
                                                <td>Thẻ vô cực</td>
                                                <td class="text-start"><strong><?=$data->thevocuc;?></strong></td>
                                            </tr>
                                            <tr>
                                                <td>Hạng</td>
                                                <td class="text-start">
                                                    <strong><?=FreeFire::rank($data->rank);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'roblox' ): ?>
                                            <tr>
                                                <td>Thể loại</td>
                                                <td class="text-start">
                                                    <strong><?=Roblox::Category($data->category);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'genshin-impact' ): ?>
                                            <tr>
                                                <td>Server</td>
                                                <td class="text-start">
                                                    <strong><?=GenshinImpact::server($data->server);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>AR</td>
                                                <td class="text-start">
                                                    <strong><?=GenshinImpact::server($data->ar);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Nhân vật</td>
                                                <td class="text-start">
                                                    <strong><?=GenshinImpact::server($data->nv);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Vũ khí</td>
                                                <td class="text-start">
                                                    <strong><?=GenshinImpact::server($data->vk);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'ngoc-rong-online' ): ?>
                                            <tr>
                                                <td>Hành Tinh</td>
                                                <td class="text-start">
                                                    <strong><?=NgocRong::planet($data->planet);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Server</td>
                                                <td class="text-start">
                                                    <strong><?=NgocRong::server($data->server);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Bông Tai</td>
                                                <td class="text-start">
                                                    <strong><?=NgocRong::earring($data->earring);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'fifa-online' ): ?>
                                            <tr>
                                                <td>Giá trị đội hình</td>
                                                <td class="text-start">
                                                    <strong><?=$data->squad_value;?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>BP Trắng</td>
                                                <td class="text-start">
                                                    <strong><?=$data->bpwhite;?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'dot-kich' ): ?>
                                            <tr>
                                                <td>Chuyên</td>
                                                <td class="text-start">
                                                    <strong><?=DotKich::chuyen($data->chuyen);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Số VIP</td>
                                                <td class="text-start">
                                                    <strong><?=$data->VIPnumber;?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'pubg-mobile' ): ?>
                                            <tr>
                                                <td>Skin súng</td>
                                                <td class="text-start">
                                                    <strong><?=$data->skin;?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Trang phục</td>
                                                <td class="text-start">
                                                    <strong><?=$data->fashion;?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'zing-speed-mobile' ): ?>
                                            <tr>
                                                <td>Giới tính</td>
                                                <td class="text-start">
                                                    <strong><?=ZingSpeed::sex($key->sex);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'play-together' ): ?>
                                            <tr>
                                                <td>Thời trang</td>
                                                <td class="text-start">
                                                    <strong><?=PlayTogether::fashion($data->fashion);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <?php if ($acc->game == 'lien-quan'  || $acc->game == 'toc-chien'|| $acc->game == 'lien-minh' ): ?>
                                            <tr>
                                                <td>Tướng</td>
                                                <td class="text-start"><strong><?=$data->tuong;?></strong></td>
                                            </tr>
                                            <tr>
                                                <td>Trang phục</td>
                                                <td class="text-start"><strong><?=$data->skin;?></strong></td>
                                            </tr>
                                            <tr>
                                                <td>Hạng</td>
                                                <td class="text-start">
                                                    <strong><?=LienQuan::rank($data->rank);?></strong>
                                                </td>
                                            </tr>
                                            <?php endif;?>
                                            <tr>
                                                <td>Thông tin</td>
                                                <td class="text-start"><strong><?=Game::info($acc->info);?></strong>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Đăng nhập</td>
                                                <td class="text-start"><strong><?=$acc->login;?></strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="let-checkout">
                                    <div class="ta-account-promo">
                                        <a href="javascript:void(0)" class="fs-14 text-primary fw-bold d-block mb-2 "
                                            id="addCode">
                                            Bấm để sử dụng mã khuyến mãi
                                        </a>
                                        <form action="/api/account/promo" method="POST" class="d-none" id="addPromo">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <input type="hidden" name="id" value="<?=$acc->id;?>">
                                                    <input type="search" placeholder="Mã khuyến mãi" name="promo_code"
                                                        class="form-control is-undefined">
                                                    <button type="submit" class="btn btn-secondary rounded-end">
                                                        Áp dụng
                                                    </button>
                                                    <!---->
                                                </div>
                                                <div id="noti"></div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="checkout-summary my-2">
                                        <!---->
                                        <div class="summary">
                                            <div class="fs-14 text-muted">Tổng thanh toán</div>
                                            <div class="fw-bold fs-4">
                                                <span id="price">
                                                    <?=format_number($acc->price);?>đ
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <form action="/api/tai-khoan-<?=$acc->game;?>/<?=$acc->id;?>/buy" method="POST"
                                        id="buy">
                                        <input type="hidden" name="promo_code" value="" id="ma_giam_gia">
                                        <button type="submit" class="btn btn-main fw-bold w-100">
                                            Mua tài khoản
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <p class="mt-3 d-block mb-0 py-2 px-3 fs-13 rounded border dashed shadow-sm bg-light"><b>Chú
                                ý:</b> Sau khi thanh toán thành công, bạn sẽ được chuyển hướng tới phần tài khoản đã mua
                            và có thể truy cập vào tài khoản đó ngay lập tức, bạn cũng có thể liên hệ người bán để được
                            hỗ trợ bảo hành tài khoản nếu có lỗi hoặc trục trặc.
                        </p>
                    </div>
                </div>
            </div>
            <!---->
            <!---->
        </div>
    </div>
</div>
<div class="modal fade" id="buyaccount" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold d-flex align-items-center"><img height="30"
                        title="Logo <?=Game::type($acc->game);?>" alt="Logo <?=Game::type($acc->game);?>"
                        src="/categories/<?=$acc->game;?>.jpg" class="rounded"> <span class="ps-2">
                        Tài Khoản <?=Game::type($acc->game);?> #<?=$acc->id;?>
                    </span>
                </h5>
                <button type="button" data-bs-dismiss="modal" aria-label="Close" class="btn-close"></button>
            </div>
            <div class="modal-body">
                <p class="mb-0 fs-14">
                    Bạn đang tiến hành mua <b>Tài Khoản <?=Game::type($acc->game);?></b> với mã số là
                    <b>#<?=$acc->MTK;?></b>, vui lòng bấm <b>xác
                        nhận mua</b> để hệ thống xử lý giao dịch của bạn... <br>
                </p>
            </div>
            <div class="modal-footer"><button type="button" class="btn btn-main flex-1 me-1" buy>Xác nhận mua</button>
                <button type="button" data-bs-dismiss="modal" class="btn btn-light flex-1 ms-1">Đóng</button>
            </div>
        </div>
    </div>
</div>
<?php include_once __DIR__ . '/../layouts/footer.phtml';?>
<?php include_once __DIR__ . '/../layouts/script.phtml';?>

<script type="text/javascript" src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/medium-zoom@1.0.3/dist/medium-zoom.min.js"></script>
<script>
$(document).ready(function() {
    $('.slide-main').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
    });
    $('.share-link').on('click', () => {
        if (navigator.share) {
            navigator.share({
                    url: '/tai-khoan-<?=$acc->game;?>/<?=$acc->id;?>',
                })
                .then(() => console.log('Chia sẻ thành công'))
                .catch((error) => console.log('Error sharing', error));
        } else {
            console.log('Share not supported on this browser, do it the old way.');
        }
    });
});
$("#buy").submit(function(e) {
    e.preventDefault();
    $("#buyaccount").modal('show');

    $("#buyaccount button[buy]").click(function() {
        CurlHttp($("#buy").attr("action"), $("#buy").attr("method"), new FormData($("#buy")[0]), $(
            "#buy").find('button[type=submit]'));
    });

});
$("#addPromo").submit(function(e) {
    e.preventDefault();
    var button = $(this).find('button[type=submit]');
    let textButton = $(this).find('button[type=submit]').html().trim();
    $.ajax({
        type: $(this).attr("method"),
        url: $(this).attr("action"),
        data: $(this).serialize(),
        dataType: "json",
        statusCode: {
            403: function() {
                $("#ma_giam_gia").val("");
                noti("error", "Đường dẫn API không chính xác");
            },
            404: function() {
                $("#ma_giam_gia").val("");
                noti("error", "Đường dẫn API không chính xác");
            },
            500: function() {
                $("#ma_giam_gia").val("");
                noti("danger", "500 status code! server error");
            },
            400: function(response) {
                let data = JSON.parse(response.responseText);
                if (!data && data == "undefined") {
                    $("#ma_giam_gia").val("");
                    noti("error", "Không thể lấy dữ liệu");
                } else {
                    if (data.href) {
                        setInterval(() => {
                            window.location.href = data.href;
                        }, 700);
                    }
                    $("#ma_giam_gia").val("");
                    $("#addPromo input[type=search]").attr('class', 'form-control is-invalid')
                    $("#addPromo #noti").attr('class', 'pt-1 invalid-feedback').html(data.message)
                }
            },
            401: function(response) {
                let data = JSON.parse(response.responseText);
                if (!data && data == "undefined") {
                    $("#ma_giam_gia").val("");
                    noti("error", "Không thể lấy dữ liệu");
                } else {
                    if (data.href) {
                        setInterval(() => {
                            window.location.href = data.href;
                        }, 700);
                    }
                    $("#ma_giam_gia").val("");
                    $("#addPromo input[type=search]").attr('class', 'form-control is-invalid')
                    $("#addPromo #noti").attr('class', 'pt-1 invalid-feedback').html(data.message)
                }
            }
        },
        beforeSend: function() {
            $("body").append(
                `<div class="ta-loader"><div role="status" class="spinner-border text-main" style="width: 3.5rem; height: 3.5rem; animation-duration: 0.8s; border-width: 0.35em;"><span class="sr-only">Loading...</span></div></div>`
            );

            button
                .prop("disabled", !0)
                .html('<i class="fas fa-spinner fa-spin"></i> Đang tải...');
        },
        complete: function() {
            button.prop("disabled", !1).html(textButton);
            $(`.ta-loader`).remove();
        },
        success: (data) => {
            if (!data && data == "undefined") {
                $("#ma_giam_gia").val("");
                noti("error", "Không thể lấy dữ liệu");
            } else {
                if (data.href) {
                    setInterval(() => {
                        window.location.href = data.href;
                    }, 700);
                }

                if (data.price) {
                    $("#price").html(data.price + 'đ');
                }

                if (data.status == 'success') {
                    $("#addPromo input[type=search]").attr('class', 'form-control is-valid');
                    $("#ma_giam_gia").val(data.promo_code);
                    $("#addPromo #noti").attr('class', 'pt-1 valid-feedback').html(data.message);
                } else {
                    $("#ma_giam_gia").val("");
                    $("#addPromo input[type=search]").attr('class', 'form-control is-invalid')
                    $("#addPromo #noti").attr('class', 'pt-1 invalid-feedback').html(data.message)
                }

            }
        },
    });
});


$('.slide-container').slick({
    slidesToShow: 4,
    slidesToScroll: 1,
    asNavFor: '.slide-main',
    focusOnSelect: true,
    arrows: true,
    responsive: [{
        breakpoint: 1024,
        settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: false,
            arrows: true,
            focusOnSelect: true,
        }
    }, ]
});

$("#addCode").click(function(e) {
    $(this).find('~ form').toggleClass('d-none').find(' input[name="promo_code"]').val('');
});

$(".slide-zoom").click(() => {
    const images = Array.from(document.querySelectorAll(".slide-main .slick-slide  img"));
    images.forEach(img => {
        mediumZoom(img, {
            margin: 0,
            /* The space outside the zoomed image */
            background: "#000",
            /* The background of the overlay */
            scrollOffset: 40,
            /* The number of pixels to scroll to close the zoom */
            container: null,
            /* The viewport to render the zoom in */
            template: null /* The template element to display on zoom */
        });

    });
    var zoomAuto = setInterval(() => {
        $(".slide-main .slick-current.slick-active img").click();
        clearInterval(zoomAuto);
    }, 0);
})
</script>
<?php include_once __DIR__ . '/../layouts/end.phtml';?>