<?php include_once __DIR__ . '/../../layouts/head.phtml';
include_once __DIR__ . '/../../layouts/navbar.phtml';
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h2 class="page-title">Bảng điều khiển</h2>
            <div class="row">
                <?php include_once __DIR__ . '/../menu.phtml';?>
                <div class="col-lg-9 info-container">
                    <div class="card">
                        <div class="card-body card-table">
                            <h5 class="card-title d-flex align-items-center justify-content-between">
                                <span>Quản lý Nạp thẻ</span>
                            </h5>
                            <table class="table table-hover table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Loại thẻ</th>
                                        <th>Mã thẻ</th>
                                        <th>Serial</th>
                                        <th>Số tiền</th>
                                        <th>Phản hồi</th>
                                        <th>Trạng thái</th>
                                        <th>Thời gian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach (Card::find()->all() as $col): ?>
                                    <tr>
                                        <td>#<?=$col->id;?></td>
                                        <td><?=$col->telco;?></td>
                                        <td><?=$col->pin;?></td>
                                        <td><?=$col->serial;?></td>
                                        <td><?=format_number2($col->amount);?></td>
                                        <td><?=$col->note;?></td>
                                        <td><?=Card::status($col->status);?></td>
                                        <td><?=timeago($col->createDate);?></td>
                                    </tr>
                                    <?php endforeach;?>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
include_once __DIR__ . '/../../layouts/footer.phtml';
include_once __DIR__ . '/../../layouts/script.phtml';
?>
<script>
$(function() {
    $('.profile-item a[href="' + location.pathname + '"]').addClass('nuxt-link-exact-active nuxt-link-active')
        .attr("aria-current", "page").parent(1).addClass('active')
});
</script>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>