<?php include_once __DIR__ . '/../layouts/head.phtml'; 
include_once __DIR__ . '/../layouts/navbar.phtml'; 
// include_once __DIR__ . '/../layouts/menu.phtml'; 
?>
<div class="ta-content">
    <div class="shop-profile">
        <!---->
        <div class="py-3 border-bottom">
            <div class="ta-container">
                <div class="d-flex shop-context">
                    <div class="d-flex align-items-center shop-header">
                        <div class="avatar"><img title="Ảnh đại diện duogxaolin" alt="Ảnh đại diện duogxaolin"
                                class="rounded-circle img-thumbnail shadow-sm" src="<?=$users->avatar;?>">
                        </div>
                        <div class="info ps-3 pt-2 pt-sm-0">
                            <h2 class="name mb-1 fw-bold"><?=$users->fullname;?></h2>
                            <div class="username fs-14 text-muted">@<?=$users->username;?></div>
                            <div class="social pt-2">
                                <?php if(!empty($shop->facebook)):?>
                                <a href="<?=$shop->facebook;?>" target="_blank">
                                    <img height="30" alt="" class="ta-lz-load ta-lz-loaded" src="/img/facebook.png">
                                </a>
                                <?php endif;?>
                                <?php if(!empty($shop->zalo)):?>
                                <a href="https://zalo.me/<?=$shop->zalo;?>" target="_blank">
                                    <img height="30" alt="" class="ta-lz-load ta-lz-loaded" src="/img/zalo.png">
                                </a>
                                <?php endif;?>
                                <?php if(!empty($shop->facebook)):?>
                                <div class="d-block d-sm-inline mt-3 mt-sm-0">
                                    <button class="btn btn-info btn-sm text-white fs-13"><i
                                            class="fal fa-phone fa-rotate-90"></i> <?=$shop->hotline;?>
                                    </button>
                                </div>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </div>
                <p class="bio fs-14 mb-0 mt-0 mt-sm-3 text-pre-wrap text-main"><?=$shop->content;?></p>
            </div>
        </div>
        <div class="ta-container pt-3">
            <div class="shop-navigation">
                <div class="row gx-sm-3 gx-2">
                    <div class="col-4">
                        <div class="profile-navigation home"><a href="/shop/<?=$users->username;?>"
                              class=""><i
                                    class="fad fa-home"></i> <span class="text">Trang chủ</span></a></div>
                    </div>
                    <div class="col-4">
                        <div class="profile-navigation review"><a href="/shop/<?=$users->username;?>/reviews"
                                class=""><i class="fad fa-star"></i> <span class="text">Đánh giá</span></a></div>
                    </div>
                    <div class="col-4">
                        <div class="profile-navigation community active"><a href="/shop/<?=$users->username;?>/community"
                        class="nuxt-link-exact-active nuxt-link-active" aria-current="page"><i class="fad fa-flag"></i> <span class="text">Cộng đồng</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ta-container pt-3">
            <h4 class="mb-2 fw-bold fs-18">Giao dịch tại Shop</h4>
            <div class="marquee-text-wrap">
                <div class="marquee-text-content">
                    <div class="marquee-text-text" style="animation-duration: 44s;">
                        <?php foreach ($buy as $marquee):?>
                        <?php $User = DB::connect()->find("users",['uid'=>$marquee->UserID])->get(); ?>
                        <?php $Shopx = DB::connect()->find("shop",['id'=>$marquee->ShopID])->get(); ?>
                        <?php $ShopUser = DB::connect()->find("users",['uid'=>$Shopx->UserID])->get(); ?>
                        <div class="py-1 px-2 mx-2 rounded fs-13 d-inline-block bg-light border border-gray"><img
                                height="25" width="29" alt="" class="rounded-circle pe-1" src="<?=$User->avatar;?>">
                            <b><?=$User->fullname;?></b> đã mua tài khoản <b><?=Game::type($marquee->game);?>
                                #<?=$marquee->id;?></b> tại Shop <a href="/shop/<?=$ShopUser->username;?>"
                                class="fw-bold"><?=$ShopUser->fullname;?></a> với giá <b
                                class="text-teal"><?=format_number($marquee->price);?>đ</b>
                        </div>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="ta-container pt-3">
                <h4 class="page-title">Bài viết trong cộng đồng</h4>
                <?php $i=0; foreach($post as $item): $i++;?>
                <div class="post shadow-sm bg-white rounded mb-3 border">
                    <div class="post-context p-3">
                        <div class="post-header">
                            <div class="user mb-2">
                                <div class="avatar"><img height="42" alt=""
                                        class="rounded-circle ta-lz-load ta-lz-loaded" src="<?=$users->avatar;?>">
                                </div>
                                <div class="info ps-2">
                                    <h4 class="fs-15 mb-0"><a href="/shop/<?=$users->username;?>" class="">
                                            <span class="name"><?=$users->fullname;?></span></a>
                                        <?php if($users->level == 4):?>
                                        <span><i class="fad fa-shield text-primary"></i></span>
                                        <?Php endif;?>
                                    </h4> <a href="/cong-dong/post/<?=$item->id;?>"
                                        class="text-secondary hover-line fs-13">
                                        <?=timeago($item->createDate);?>
                                    </a>
                                </div>
                            </div>
                            <div class="action">
                                <div class="dropdown"><button type="button" data-bs-toggle="dropdown"
                                        data-bs-display="static" aria-expanded="false"
                                        class="btn btn-light btn-action"><i class="fa fa-ellipsis-h"></i></button>
                                    <ul class="dropdown-menu dropdown-menu-end mt-2">
                                        <!---->
                                        <li>
                                            <a href="javascript:void(0)"
                                                onclick="copy('<?=base_url();?>/cong-dong/post/<?=$item->id;?>')"
                                                class="dropdown-item text-secondary"><i class="fad fa-link"></i> Sao
                                                chép liên kết
                                            </a>
                                        </li>
                                        <!---->
                                        <!---->
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <p class="post-content my-2 fs-14"><?=$item->content;?></p>
                    </div>
                    <div class="post-action border-top border-bottom">
                        <div class="action like cursor-pointer"><i class="fal fa-heart"></i> <b class="count">0</b>
                            <span class="text">Thích</span>
                        </div>
                        <div class="action"><i class="fal fa-comment"></i> <b class="count">0</b> <span
                                class="text">Bình luận</span></div>
                        <div class="action cursor-pointer"><i class="fal fa-share"></i> <span class="text">Chia
                                sẻ</span></div>
                    </div>
                    <!---->
                    <div class="my-comment p-3 pt-3">
                        <div class="d-flex align-items-center">
                            <div class="avatar">
                                <img height="38" alt="" class="rounded-circle ta-lz-load ta-lz-loaded"
                                    src="<?=(Auth::check()) ? Auth::user()->avatar :'/default_avatar.png' ?> ">
                            </div>
                            <div class="comment ps-2 w-100">
                                <form action="">
                                    <div class="input-group"><input type="search"
                                            placeholder="Nhập nội dung bình luận..." required="required"
                                            class="form-control d-inline-block"> <button
                                            class="ta-submit btn btn-main fs-12"><i
                                                class="fad fa-paper-plane"></i></button></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach;?>
                <?php if(empty($i)):?>
                <div class="pt-4 text-center min-h-200">
                    <div class="icon"><i class="fad fa-flag text-info fa-5x"></i></div>
                    <h4 class="fw-bold text-muted mt-3">Chưa có bài viết!</h4>
                </div>
                <?php endif;?>


                <!---->
            </div>
        </div>
    </div>
</div>
<?php 
include_once __DIR__ . '/../layouts/footer.phtml'; 
include_once __DIR__ . '/../layouts/script.phtml'; 
include_once __DIR__ . '/../layouts/end.phtml'; 
?>