<?php include_once __DIR__ . '/../../layouts/head.phtml';
include_once __DIR__ . '/../../layouts/navbar.phtml';
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h2 class="page-title">Bảng điều khiển</h2>
            <div class="row">
                <?php include_once __DIR__ . '/../menu.phtml';?>
                <div class="col-lg-9 info-container">
                    <div class="card">
                        <div class="card-body card-table">
                            <h5 class="card-title d-flex align-items-center justify-content-between">
                                <span>Quản lý thành viên</span>
                            </h5>
                            <table class="table table-hover table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Thao tác</th>
                                        <th>Tài khoản</th>
                                        <th>Email</th>
                                        <th>Cửa hàng</th>
                                        <th>Số dư</th>
                                        <th>Cấp bậc</th>
                                        <th>Trạng thái</th>
                                        <th>Thời gian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach (Auth::all() as $users): ?>
                                    <tr>
                                        <td><?=$users->uid;?></td>
                                        <td>
                                            <a href="/admin/member/<?=$users->uid;?>/edit"
                                                class="btn btn-primary btn-action">
                                                <i class="fa fa-pencil-alt"></i></a>
                                            <a href="/admin/member/<?=$users->uid;?>/delete">

                                                <button class="btn btn-danger btn-action">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img width="24" height="24" alt="" src="<?=$users->avatar;?>"
                                                    class="img-navbar rounded-circle shadow-sm me-1">
                                                <div class="ms-1">
                                                    <?=$users->fullname;?>
                                                </div>
                                            </div>
                                        </td>
                                        <td><?=$users->email;?></td>
                                        <td>0</td>
                                        <td class="fw-bold">
                                            <?=format_number2($users->money);?>đ
                                        </td>
                                        <td><?=Auth::level($users->level);?></td>
                                        <td><?=Auth::status($users->status);?></td>
                                        <td><?=timeago($users->createDate);?></td>
                                    </tr>
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
include_once __DIR__ . '/../../layouts/footer.phtml';
include_once __DIR__ . '/../../layouts/script.phtml';
?>
<script>
$(function() {
    $('.profile-item a[href="' + location.pathname + '"]').addClass('nuxt-link-exact-active nuxt-link-active')
        .attr("aria-current", "page").parent(1).addClass('active')
});
</script>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>