<?php include_once __DIR__ . '/../../layouts/head.phtml';
include_once __DIR__ . '/../../layouts/navbar.phtml';
?>
<div class="ta-content">
    <div class="ta-container py-3 pb-sm-4 pt-sm-3">
        <div>
            <h2 class="page-title">Bảng điều khiển</h2>
            <div class="row">
                <?php include_once __DIR__ . '/../menu.phtml';?>
                <div class="col-lg-9 info-container">
                    <div class="card">
                        <div class="card-body card-table">
                            <h5 class="card-title d-flex align-items-center justify-content-between">
                                <span>Quản lý yêu cầu rút tiền</span>
                            </h5>
                            <table class="table table-hover table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Thao tác</th>
                                        <th>Tài khoản</th>
                                        <th>Số tài khoản</th>
                                        <th>Chủ tài khoản</th>
                                        <th>Ngân hàng</th>
                                        <th>Số tiền rút</th>
                                        <th>Thực nhận</th>
                                        <th>nhận</th>
                                        <th>Chiết khấu</th>
                                        <th>Trạng thái</th>
                                        <th>Thời gian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach (withdraw::find()->all() as $col): ?>
                                    <?php $shop = DB::connect()->find("shop", ['id' => $col->ShopID])->get();?>
                                    <?php $users = DB::connect()->find("users", ['uid' => $shop->UserID])->get();?>
                                    <tr>
                                        <td><?=$col->id;?></td>
                                        <td>
                                            <?php if ($col->status != "pending"): ?>
                                            <a href="/admin/rut/<?=$col->id;?>/duyet"
                                                class="btn btn-primary btn-action">
                                                Duyệt</a>
                                            <a href="/admin/rut/<?=$col->id;?>/tuchoi">
                                                <button class="btn btn-danger btn-action">
                                                    Từ chối
                                                </button>
                                            </a>
                                            <?php else: ?>
                                            Không thể hực hiện
                                            <?Php endif;?>
                                        </td>
                                        <td class="d-flex flex-column">
                                            <div class="d-flex align-items-center">
                                                <img width="24" height="24" alt="" src="<?=$users->avatar;?>"
                                                    class="img-navbar rounded-circle shadow-sm me-1">
                                                <div class="ms-1">
                                                    <?=$users->fullname;?>
                                                </div>
                                            </div>
                                        </td>
                                        <td><?=$col->stk;?></td>
                                        <td><?=$col->ctk;?></td>
                                        <td><?=$col->bank;?></td>
                                        <td>
                                            <?=format_number2($col->quantity);?>
                                        </td>
                                        <td><?=format_number2($col->thucnhan);?></td>
                                        <td><?=StatusNhan($col->nhan);?></td>
                                        <td>
                                            <?=Setting::find('phirut');?>%
                                        </td>
                                        <td><?=withdraw::status($col->status);?></td>
                                        <td><?=timeago($col->createDate);?></td>
                                    </tr>
                                    <?php endforeach;?>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
include_once __DIR__ . '/../../layouts/footer.phtml';
include_once __DIR__ . '/../../layouts/script.phtml';
?>
<script>
$(function() {
    $('.profile-item a[href="' + location.pathname + '"]').addClass('nuxt-link-exact-active nuxt-link-active')
        .attr("aria-current", "page").parent(1).addClass('active')
});
</script>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>